export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** Represents untyped JSON */
  JSON: any;
};

export type Affiliation = {
  __typename?: 'Affiliation';
  role: Scalars['String'];
  tenantId: Scalars['ID'];
  tenantName: Scalars['String'];
};

export type AffiliationInput = {
  id: Scalars['Int'];
  tenantName: Scalars['String'];
};

export type Conference = {
  __typename?: 'Conference';
  id: Scalars['Int'];
  name: Scalars['String'];
  participants: Array<Participant>;
};

export type ConferenceInput = {
  id?: Maybe<Scalars['Int']>;
  name: Scalars['String'];
  password?: Maybe<Scalars['String']>;
  participants?: Maybe<Array<ParticipantInput>>;
};

export type ConferenceMutation = {
  __typename?: 'ConferenceMutation';
  createConference?: Maybe<CreateConferenceMutationPayload>;
  updateConference?: Maybe<UpdateConferenceMutationPayload>;
};


export type ConferenceMutationCreateConferenceArgs = {
  conference: ConferenceInput;
};


export type ConferenceMutationUpdateConferenceArgs = {
  conference: ConferenceInput;
};

/** Autogenerated return type of CreateConferenceMutation */
export type CreateConferenceMutationPayload = {
  __typename?: 'CreateConferenceMutationPayload';
  conference: Conference;
};

/** Autogenerated return type of CreateUserMutation */
export type CreateUserMutationPayload = {
  __typename?: 'CreateUserMutationPayload';
  user: User;
};

/** Autogenerated return type of CreateVerificationMutation */
export type CreateVerificationMutationPayload = {
  __typename?: 'CreateVerificationMutationPayload';
  verification: Verification;
};

export type Credential = {
  __typename?: 'Credential';
  accessToken: Scalars['String'];
  client: Scalars['String'];
  expiry: Scalars['Int'];
  tokenType: Scalars['String'];
  uid: Scalars['String'];
};

/** Autogenerated return type of DeleteUserMutation */
export type DeleteUserMutationPayload = {
  __typename?: 'DeleteUserMutationPayload';
  user: User;
};

export type Dossier = {
  __typename?: 'Dossier';
  affiliation: Affiliation;
  candidate: Person;
  companyContact?: Maybe<Person>;
  companyMarkA?: Maybe<Scalars['String']>;
  companyMarkB?: Maybe<Scalars['String']>;
  companyPointsA?: Maybe<Scalars['String']>;
  companyPointsB?: Maybe<Scalars['String']>;
  dossierPath?: Maybe<Scalars['String']>;
  expertMarkA?: Maybe<Scalars['String']>;
  expertMarkB?: Maybe<Scalars['String']>;
  expertMarkC?: Maybe<Scalars['String']>;
  expertPointsA?: Maybe<Scalars['String']>;
  expertPointsB?: Maybe<Scalars['String']>;
  expertPointsC?: Maybe<Scalars['String']>;
  finalMark?: Maybe<Scalars['String']>;
  id: Scalars['Int'];
  markDeduction?: Maybe<Scalars['Boolean']>;
  primaryExpert?: Maybe<Person>;
  secondaryExpert?: Maybe<Person>;
  submittedMark?: Maybe<Scalars['String']>;
};

export type DossierInput = {
  id?: Maybe<Scalars['Int']>;
  affiliation: AffiliationInput;
  candidate: PersonInput;
  primaryExpert?: Maybe<PersonInput>;
  secondaryExpert?: Maybe<PersonInput>;
  companyContact?: Maybe<PersonInput>;
  conferenceId: Scalars['Int'];
  companyPointsA?: Maybe<Scalars['String']>;
  companyPointsB?: Maybe<Scalars['String']>;
  companyMarkA?: Maybe<Scalars['String']>;
  companyMarkB?: Maybe<Scalars['String']>;
  expertPointsA?: Maybe<Scalars['String']>;
  expertPointsB?: Maybe<Scalars['String']>;
  expertPointsC?: Maybe<Scalars['String']>;
  expertMarkA?: Maybe<Scalars['String']>;
  expertMarkB?: Maybe<Scalars['String']>;
  expertMarkC?: Maybe<Scalars['String']>;
  markDeduction?: Maybe<Scalars['Boolean']>;
  finalMark?: Maybe<Scalars['String']>;
  submittedMark?: Maybe<Scalars['String']>;
  dossierPath?: Maybe<Scalars['String']>;
};

export type Evaluation = {
  __typename?: 'Evaluation';
  result: Scalars['JSON'];
};

/** Autogenerated return type of ImportMutation */
export type ImportMutationPayload = {
  __typename?: 'ImportMutationPayload';
  importCount: Scalars['Int'];
};


export type Mutation = {
  __typename?: 'Mutation';
  conferences?: Maybe<ConferenceMutation>;
  pkorg?: Maybe<PkorgMutation>;
  userLogin?: Maybe<UserLoginPayload>;
  userLogout?: Maybe<UserLogoutPayload>;
  users?: Maybe<UserMutation>;
  verifications?: Maybe<VerificationMutation>;
};


export type MutationPkorgArgs = {
  sessionToken: Scalars['String'];
  baseUrl: Scalars['String'];
  userAgent?: Maybe<Scalars['String']>;
};


export type MutationUserLoginArgs = {
  email: Scalars['String'];
  password: Scalars['String'];
};

export type Participant = {
  __typename?: 'Participant';
  email: Scalars['String'];
  forename: Scalars['String'];
  id: Scalars['Int'];
  surname: Scalars['String'];
};

export type ParticipantInput = {
  id?: Maybe<Scalars['Int']>;
  forename: Scalars['String'];
  surname: Scalars['String'];
  email: Scalars['String'];
};

export type Person = {
  __typename?: 'Person';
  forename: Scalars['String'];
  id: Scalars['Int'];
  surname: Scalars['String'];
};

export type PersonInput = {
  id: Scalars['Int'];
  forename: Scalars['String'];
  surname: Scalars['String'];
};

export type PkorgMutation = {
  __typename?: 'PkorgMutation';
  importDossiers?: Maybe<ImportMutationPayload>;
};


export type PkorgMutationImportDossiersArgs = {
  dossiers: Array<DossierInput>;
};

export type PkorgQuery = {
  __typename?: 'PkorgQuery';
  evaluation?: Maybe<Evaluation>;
  sessionUser?: Maybe<SessionUser>;
};


export type PkorgQueryEvaluationArgs = {
  evaluationPath: Scalars['String'];
};

export type Query = {
  __typename?: 'Query';
  conferences?: Maybe<Array<Conference>>;
  dossiers?: Maybe<Array<Dossier>>;
  pkorg?: Maybe<PkorgQuery>;
  users?: Maybe<Array<User>>;
  verificationResults?: Maybe<Array<VerificationResult>>;
};


export type QueryConferencesArgs = {
  id?: Maybe<Scalars['Int']>;
};


export type QueryDossiersArgs = {
  id?: Maybe<Scalars['Int']>;
};


export type QueryPkorgArgs = {
  sessionToken: Scalars['String'];
  baseUrl: Scalars['String'];
  userAgent?: Maybe<Scalars['String']>;
};


export type QueryUsersArgs = {
  id?: Maybe<Scalars['Int']>;
};


export type QueryVerificationResultsArgs = {
  token: Scalars['String'];
};

export type SessionUser = {
  __typename?: 'SessionUser';
  affiliations: Array<Affiliation>;
  email: Scalars['String'];
  forename: Scalars['String'];
  surname: Scalars['String'];
};

/** Autogenerated return type of UpdateConferenceMutation */
export type UpdateConferenceMutationPayload = {
  __typename?: 'UpdateConferenceMutationPayload';
  conference: Conference;
};

/** Autogenerated return type of UpdateUserMutation */
export type UpdateUserMutationPayload = {
  __typename?: 'UpdateUserMutationPayload';
  user: User;
};

export type User = {
  __typename?: 'User';
  email: Scalars['String'];
  id: Scalars['Int'];
  name?: Maybe<Scalars['String']>;
  nickname?: Maybe<Scalars['String']>;
};

export type UserInput = {
  id?: Maybe<Scalars['Int']>;
  email: Scalars['String'];
  name: Scalars['String'];
  password?: Maybe<Scalars['String']>;
  passwordConfirmation?: Maybe<Scalars['String']>;
  nickname?: Maybe<Scalars['String']>;
};

/** Autogenerated return type of UserLogin */
export type UserLoginPayload = {
  __typename?: 'UserLoginPayload';
  authenticatable: User;
  credentials: Credential;
};

/** Autogenerated return type of UserLogout */
export type UserLogoutPayload = {
  __typename?: 'UserLogoutPayload';
  authenticatable: User;
};

export type UserMutation = {
  __typename?: 'UserMutation';
  createUser?: Maybe<CreateUserMutationPayload>;
  deleteUser?: Maybe<DeleteUserMutationPayload>;
  updateUser?: Maybe<UpdateUserMutationPayload>;
};


export type UserMutationCreateUserArgs = {
  user: UserInput;
};


export type UserMutationDeleteUserArgs = {
  id: Scalars['Int'];
};


export type UserMutationUpdateUserArgs = {
  id: Scalars['Int'];
  user: UserInput;
};

export type Verification = {
  __typename?: 'Verification';
  email: Scalars['String'];
  id: Scalars['Int'];
};

export type VerificationInput = {
  id?: Maybe<Scalars['Int']>;
  email: Scalars['String'];
  dossierId: Scalars['Int'];
};

export type VerificationMutation = {
  __typename?: 'VerificationMutation';
  createVerification?: Maybe<CreateVerificationMutationPayload>;
};


export type VerificationMutationCreateVerificationArgs = {
  verification: VerificationInput;
};

export type VerificationResult = {
  __typename?: 'VerificationResult';
  dossier: Dossier;
  email: Scalars['String'];
  id: Scalars['Int'];
};

export type SignInMutationVariables = Exact<{
  email: Scalars['String'];
  password: Scalars['String'];
}>;


export type SignInMutation = (
  { __typename?: 'Mutation' }
  & { userLogin?: Maybe<(
    { __typename?: 'UserLoginPayload' }
    & { authenticatable: (
      { __typename?: 'User' }
      & Pick<User, 'email' | 'name'>
    ), credentials: (
      { __typename?: 'Credential' }
      & Pick<Credential, 'accessToken' | 'client' | 'expiry' | 'tokenType' | 'uid'>
    ) }
  )> }
);

export type ReadUserQueryVariables = Exact<{
  id: Scalars['Int'];
}>;


export type ReadUserQuery = (
  { __typename?: 'Query' }
  & { users?: Maybe<Array<(
    { __typename?: 'User' }
    & Pick<User, 'id' | 'email' | 'name' | 'nickname'>
  )>> }
);

export type UpdateUserMutationVariables = Exact<{
  id: Scalars['Int'];
  user: UserInput;
}>;


export type UpdateUserMutation = (
  { __typename?: 'Mutation' }
  & { users?: Maybe<(
    { __typename?: 'UserMutation' }
    & { updateUser?: Maybe<(
      { __typename?: 'UpdateUserMutationPayload' }
      & { user: (
        { __typename?: 'User' }
        & Pick<User, 'id' | 'email' | 'name' | 'nickname'>
      ) }
    )> }
  )> }
);

export type IndexUsersQueryVariables = Exact<{ [key: string]: never; }>;


export type IndexUsersQuery = (
  { __typename?: 'Query' }
  & { users?: Maybe<Array<(
    { __typename?: 'User' }
    & Pick<User, 'id' | 'email' | 'name' | 'nickname'>
  )>> }
);

export type DeleteUserMutationVariables = Exact<{
  id: Scalars['Int'];
}>;


export type DeleteUserMutation = (
  { __typename?: 'Mutation' }
  & { users?: Maybe<(
    { __typename?: 'UserMutation' }
    & { deleteUser?: Maybe<(
      { __typename?: 'DeleteUserMutationPayload' }
      & { user: (
        { __typename?: 'User' }
        & Pick<User, 'id'>
      ) }
    )> }
  )> }
);

export type CreateUserMutationVariables = Exact<{
  user: UserInput;
}>;


export type CreateUserMutation = (
  { __typename?: 'Mutation' }
  & { users?: Maybe<(
    { __typename?: 'UserMutation' }
    & { createUser?: Maybe<(
      { __typename?: 'CreateUserMutationPayload' }
      & { user: (
        { __typename?: 'User' }
        & Pick<User, 'id' | 'email' | 'name' | 'nickname'>
      ) }
    )> }
  )> }
);

export type IndexDossiersQueryVariables = Exact<{ [key: string]: never; }>;


export type IndexDossiersQuery = (
  { __typename?: 'Query' }
  & { dossiers?: Maybe<Array<(
    { __typename?: 'Dossier' }
    & Pick<Dossier, 'id' | 'submittedMark' | 'markDeduction'>
    & { candidate: (
      { __typename?: 'Person' }
      & Pick<Person, 'forename' | 'surname' | 'id'>
    ) }
  )>> }
);

export type CreateVerificationMutationVariables = Exact<{
  verification: VerificationInput;
}>;


export type CreateVerificationMutation = (
  { __typename?: 'Mutation' }
  & { verifications?: Maybe<(
    { __typename?: 'VerificationMutation' }
    & { createVerification?: Maybe<(
      { __typename?: 'CreateVerificationMutationPayload' }
      & { verification: (
        { __typename?: 'Verification' }
        & Pick<Verification, 'id'>
      ) }
    )> }
  )> }
);

export type ReadConferenceQueryVariables = Exact<{
  id: Scalars['Int'];
}>;


export type ReadConferenceQuery = (
  { __typename?: 'Query' }
  & { conferences?: Maybe<Array<(
    { __typename?: 'Conference' }
    & Pick<Conference, 'id' | 'name'>
    & { participants: Array<(
      { __typename?: 'Participant' }
      & Pick<Participant, 'id' | 'forename' | 'surname' | 'email'>
    )> }
  )>> }
);

export type UpdateConferenceMutationVariables = Exact<{
  conference: ConferenceInput;
}>;


export type UpdateConferenceMutation = (
  { __typename?: 'Mutation' }
  & { conferences?: Maybe<(
    { __typename?: 'ConferenceMutation' }
    & { updateConference?: Maybe<(
      { __typename?: 'UpdateConferenceMutationPayload' }
      & { conference: (
        { __typename?: 'Conference' }
        & Pick<Conference, 'id' | 'name'>
      ) }
    )> }
  )> }
);

export type IndexConferencesQueryVariables = Exact<{ [key: string]: never; }>;


export type IndexConferencesQuery = (
  { __typename?: 'Query' }
  & { conferences?: Maybe<Array<(
    { __typename?: 'Conference' }
    & Pick<Conference, 'id' | 'name'>
  )>> }
);

export type CreateConferenceMutationVariables = Exact<{
  conference: ConferenceInput;
}>;


export type CreateConferenceMutation = (
  { __typename?: 'Mutation' }
  & { conferences?: Maybe<(
    { __typename?: 'ConferenceMutation' }
    & { createConference?: Maybe<(
      { __typename?: 'CreateConferenceMutationPayload' }
      & { conference: (
        { __typename?: 'Conference' }
        & Pick<Conference, 'id' | 'name'>
      ) }
    )> }
  )> }
);

export type CheckConnectionQueryVariables = Exact<{
  baseUrl: Scalars['String'];
  sessionToken: Scalars['String'];
  userAgent: Scalars['String'];
}>;


export type CheckConnectionQuery = (
  { __typename?: 'Query' }
  & { pkorg?: Maybe<(
    { __typename?: 'PkorgQuery' }
    & { sessionUser?: Maybe<(
      { __typename?: 'SessionUser' }
      & Pick<SessionUser, 'email' | 'forename' | 'surname'>
      & { affiliations: Array<(
        { __typename?: 'Affiliation' }
        & Pick<Affiliation, 'tenantName' | 'tenantId' | 'role'>
      )> }
    )> }
  )> }
);

export type ImportDossiersMutationVariables = Exact<{
  baseUrl: Scalars['String'];
  sessionToken: Scalars['String'];
  userAgent: Scalars['String'];
  dossiers: Array<DossierInput> | DossierInput;
}>;


export type ImportDossiersMutation = (
  { __typename?: 'Mutation' }
  & { pkorg?: Maybe<(
    { __typename?: 'PkorgMutation' }
    & { importDossiers?: Maybe<(
      { __typename?: 'ImportMutationPayload' }
      & Pick<ImportMutationPayload, 'importCount'>
    )> }
  )> }
);

export type RetrieveEvaluationQueryVariables = Exact<{
  baseUrl: Scalars['String'];
  sessionToken: Scalars['String'];
  userAgent: Scalars['String'];
  evaluationPath: Scalars['String'];
}>;


export type RetrieveEvaluationQuery = (
  { __typename?: 'Query' }
  & { pkorg?: Maybe<(
    { __typename?: 'PkorgQuery' }
    & { evaluation?: Maybe<(
      { __typename?: 'Evaluation' }
      & Pick<Evaluation, 'result'>
    )> }
  )> }
);
